import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { AnimatePresence, motion, useInView, useReducedMotion } from 'framer-motion'
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, Menu as MenuIcon, MessageCircle, Phone, Play, Search, Star, Utensils, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { restaurantConfig } from './data/restaurant'
import { menuItems } from './data/menu'
import { offers } from './data/offers'
import { events } from './data/events'
import { galleryItems } from './data/gallery'
import { reviews } from './data/reviews'
import './App.css'
import './theme-overrides.css'

const navItems = [['About', '/about'], ['Menu', '/menu'], ['Offers', '/offers'], ['Events', '/events'], ['Gallery', '/gallery'], ['Reviews', '/reviews'], ['Contact', '/contact']]
const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } }

function Reveal({ children, className = '', delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once: true, margin: '-12% 0px' })
  const reduceMotion = useReducedMotion()
  return <motion.div ref={ref} className={className} initial={reduceMotion ? false : 'hidden'} animate={reduceMotion || inView ? 'visible' : 'hidden'} variants={fadeUp} transition={{ duration: .7, delay, ease: [.22, 1, .36, 1] }}>{children}</motion.div>
}

function ImageReveal({ src, alt, className = '' }: { src: string; alt: string; className?: string }) {
  const reduceMotion = useReducedMotion()
  return <motion.img className={className} src={src} alt={alt} loading="lazy" initial={reduceMotion ? false : { opacity: 0, scale: 1.06 }} whileInView={reduceMotion ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true, margin: '-10% 0px' }} transition={{ duration: .9, ease: [.22, 1, .36, 1] }} />
}

function usePageMeta(title: string, description: string) {
  useEffect(() => { document.title = title; document.querySelector('meta[name="description"]')?.setAttribute('content', description) }, [title, description])
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const location = useLocation()
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 32); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  useEffect(() => { setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }, [location.pathname])
  return <div className="app-shell">
    <header className={`site-header ${scrolled || location.pathname !== '/' ? 'is-solid' : ''}`}>
      <Link className="brand" to="/" aria-label="Spot 11 Enjoy home"><span className="brand-mark">11</span><span><strong>SPOT</strong><em>ENJOY</em></span></Link>
      <nav className="desktop-nav" aria-label="Primary navigation"><NavLink to="/">Home</NavLink>{navItems.map(([label, path]) => <NavLink key={path} to={path}>{label}</NavLink>)}</nav>
      <div className="header-actions"><Link className="text-link" to="/reservation">Reserve a table</Link><a className="button button-gold button-small" href={restaurantConfig.swiggyUrl} target="_blank" rel="noreferrer">Order online <ArrowRight size={15} /></a></div>
      <button className="menu-toggle" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <MenuIcon />}</button>
    </header>
    <AnimatePresence>{menuOpen && <MobileMenu onClose={() => setMenuOpen(false)} />}</AnimatePresence>
    <main><AnimatePresence mode="wait"><motion.div className="route-stage" key={location.pathname} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .35, ease: [.22, 1, .36, 1] }}><Routes>
      <Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/menu" element={<MenuPage />} /><Route path="/offers" element={<OffersPage />} /><Route path="/events" element={<EventsPage />} /><Route path="/gallery" element={<GalleryPage />} /><Route path="/reviews" element={<ReviewsPage />} /><Route path="/contact" element={<ContactPage />} /><Route path="/reservation" element={<ReservationPage />} /><Route path="*" element={<EmptyPage title="Page not found" description="The page you are looking for is not available." />} />
    </Routes></motion.div></AnimatePresence></main><FloatingActions /><Footer />
  </div>
}

function MobileMenu({ onClose }: { onClose: () => void }) { return <motion.div className="mobile-menu" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}><nav aria-label="Mobile navigation"><NavLink to="/" onClick={onClose}>Home</NavLink>{navItems.map(([label, path]) => <NavLink key={path} to={path} onClick={onClose}>{label}</NavLink>)}</nav><div className="mobile-menu-actions"><Link className="button button-gold" to="/reservation" onClick={onClose}>Reserve a table <ArrowRight size={16} /></Link><a className="button button-outline" href={restaurantConfig.swiggyUrl} target="_blank" rel="noreferrer">Swiggy</a><a className="button button-outline" href={restaurantConfig.zomatoUrl} target="_blank" rel="noreferrer">Zomato</a></div></motion.div> }
function QuickActions() { return <section className="quick-actions page-width" aria-label="Quick actions"><a href={`tel:${restaurantConfig.phone}`}><Phone size={17} /><span>Call now</span></a><a href={restaurantConfig.googleMapsUrl} target="_blank" rel="noreferrer"><MapPin size={17} /><span>Directions</span></a><Link to="/reservation"><CalendarDays size={17} /><span>Reserve</span></Link><Link to="/menu"><Utensils size={17} /><span>View menu</span></Link></section> }
function Home() { usePageMeta('Spot 11 Enjoy | Family Restaurant & Bar in Dhanori, Pune', restaurantConfig.description); return <>
  <section className="hero"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-placeholder"><img src="/images/gallery/spot-11-google-maps-hero.jpg" alt="Food spread at Spot 11 Enjoy" /><span className="image-credit">Photo from Google Maps listing</span></div><div className="hero-content page-width"><motion.p className="eyebrow" initial="hidden" animate="visible" variants={fadeUp}>Gini Belvista · Dhanori, Pune</motion.p><motion.h1 initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .1 }}>Good food.<br /><i>Great vibes.</i><br />Unforgettable moments.</motion.h1><motion.p className="hero-copy" initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .2 }}>Family dining, bar nights and celebrations made for lingering a little longer.</motion.p><motion.div className="hero-buttons" initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .3 }}><Link className="button button-gold" to="/reservation">Reserve a table <ArrowRight size={17} /></Link><Link className="button button-ghost" to="/menu">Explore the menu <ArrowRight size={17} /></Link></motion.div></div><div className="scroll-cue"><span /> Scroll to explore</div></section>
  <QuickActions /><Reveal className="section section-intro page-width"><div className="section-kicker">01 / The place</div><div className="intro-grid"><div><p className="eyebrow">Welcome to Spot 11 Enjoy</p><h2>A place to eat,<br /><i>drink & enjoy.</i></h2></div><div><p className="lead">A new chapter in your dining story, set in Dhanori. We are preparing a space for easy afternoons, expressive plates and nights that gather everyone around the table.</p><Link className="under-link" to="/about">Discover our story <ArrowRight size={16} /></Link></div></div></Reveal>
  <Reveal><section className="experience-band"><div className="page-width experience-grid"><div className="experience-copy"><p className="eyebrow">02 / The experience</p><h2>Made for your<br /><i>kind of night.</i></h2><p>From a relaxed family meal to the first toast of the weekend, Spot 11 Enjoy is designed around the moments that matter.</p><Link className="button button-outline" to="/contact">Find us in Dhanori <MapPin size={16} /></Link></div><div className="experience-art"><span className="art-label">Your next<br /><strong>favourite table</strong></span><span className="art-line" /></div></div></section></Reveal>
  <MenuPreview /><ContentStrip title="Offers & occasions" path="/offers" item={offers[0]} empty="New offers coming soon." /><ContentStrip title="What’s on" path="/events" item={events[0]} empty="Upcoming events will appear here." />
  <Reveal className="section page-width"><div className="section-heading"><div><p className="eyebrow">05 / A first look</p><h2>Moments at <i>Spot 11.</i></h2></div><Link className="under-link" to="/gallery">View gallery <ArrowRight size={16} /></Link></div><div className="gallery-preview"><div className="photo-placeholder tall"><ImageReveal src="/images/gallery/spot-11-placejoys-1.jpg" alt="Spot 11 Enjoy dining room" /></div><div className="photo-placeholder"><ImageReveal src="/images/gallery/spot-11-placejoys-3.jpg" alt="Food served at Spot 11 Enjoy" /></div><div className="photo-placeholder"><ImageReveal src="/images/gallery/spot-11-placejoys-8.jpg" alt="Evening scene at Spot 11 Enjoy" /></div></div></Reveal><ReviewsPreview /><ReservationCTA /><ContactPreview />
</> }
function MenuPreview() { return <section className="section menu-preview page-width"><div className="section-heading"><div><p className="eyebrow">03 / From the kitchen</p><h2>A menu worth <i>talking about.</i></h2></div><Link className="under-link" to="/menu">See full menu <ArrowRight size={16} /></Link></div><div className="menu-preview-card"><div className="menu-card-art"><span>Menu photography<br />to be added</span></div><div className="menu-card-copy"><span className="number">01</span><h3>Menu content<br /><i>coming soon.</i></h3><p>Our kitchen menu is being prepared. Check back soon for dishes, details and pricing.</p><Link className="button button-outline" to="/menu">Browse menu <ArrowRight size={15} /></Link></div></div></section> }
function ContentStrip({ title, path, item, empty }: { title: string; path: string; item?: { title: string; description?: string }; empty: string }) { return <section className="section compact-section page-width"><div className="section-heading"><div><p className="eyebrow">Coming up</p><h2>{title}</h2></div><Link className="under-link" to={path}>View all <ArrowRight size={16} /></Link></div><div className="empty-panel"><CalendarDays size={22} /><div><strong>{item?.title || empty}</strong><p>{item?.description || 'Verified updates will be added here when available.'}</p></div><span className="status-pill">To be updated</span></div></section> }
function ReviewsPreview() { return <section className="review-band"><div className="page-width review-grid"><div><p className="eyebrow">06 / From our guests</p><h2>Good times are<br /><i>better shared.</i></h2></div><div className="review-empty"><div className="preview-rating"><Star size={21} /><strong>{restaurantConfig.rating}</strong><span>/ 5 customer rating</span></div><p>Based on {restaurantConfig.reviewCount} published reviews. Read the full selection and source details.</p><div className="preview-review-actions"><Link className="under-link" to="/reviews">Read reviews <ArrowRight size={16} /></Link><a className="under-link" href="https://spot-11-enjoy.placejoys.com/#reviews" target="_blank" rel="noreferrer">View source <ArrowRight size={16} /></a></div></div></div></section> }
function ReservationCTA() { return <section className="reservation-cta"><div className="page-width"><p className="eyebrow">07 / Make it yours</p><h2>Your table is<br /><i>waiting.</i></h2><p>Planning a family dinner, a birthday or simply a night out? Let’s make it a good one.</p><Link className="button button-gold" to="/reservation">Reserve a table <ArrowRight size={17} /></Link></div></section> }
function ContactPreview() { return <section className="contact-preview page-width"><div><p className="eyebrow">08 / Come by</p><h2>See you at<br /><i>Spot 11.</i></h2></div><div><p>{restaurantConfig.address.join(', ')}</p><a className="under-link" href={restaurantConfig.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <MapPin size={16} /></a></div><div><p>Call us</p><a className="phone-link" href={`tel:${restaurantConfig.phone}`}>{restaurantConfig.phone}</a></div></section> }
function PageHero({ eyebrow, title, description }: { eyebrow: string; title: ReactNode; description: string }) { return <section className="page-hero"><div className="page-width"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-hero-copy">{description}</p></div></section> }
function About() { usePageMeta('About Spot 11 Enjoy | Dhanori Pune', restaurantConfig.description); return <><PageHero eyebrow="01 / The story" title={<>A place with<br /><i>room for everyone.</i></>} description="Spot 11 Enjoy is a family restaurant, bar and dining destination in Gini Belvista, Dhanori, Pune." /><Reveal className="section page-width about-layout"><div className="photo-placeholder about-photo"><ImageReveal src="/images/gallery/spot-11-placejoys-2.jpg" alt="Spot 11 Enjoy interior" /></div><div><p className="eyebrow">Made for the everyday celebration</p><h2>Come as you are.<br /><i>Stay for the feeling.</i></h2><p className="lead">The details of our food, service and atmosphere are still being brought together. This space will become the full story of Spot 11 Enjoy as verified information is added.</p><Link className="button button-gold" to="/contact">Plan your visit <ArrowRight size={16} /></Link></div></Reveal><ExperienceDetails /></> }
function ExperienceDetails() { return <section className="section detail-section page-width"><div><span className="number">A</span><h3>Family dining</h3><p>A welcoming setting for meals shared across generations.</p></div><div><span className="number">B</span><h3>Bar & nights</h3><p>A place to ease into the evening, with details to come.</p></div><div><span className="number">C</span><h3>Celebrations</h3><p>Bring the people and let the occasion take shape.</p></div></section> }
function MenuPage() { const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const categories = ['All', ...new Set(menuItems.map(item => item.category))]; const filtered = useMemo(() => menuItems.filter(item => (category === 'All' || item.category === category) && item.name.toLowerCase().includes(query.toLowerCase())), [category, query]); usePageMeta('Spot 11 Enjoy Menu | Restaurant & Bar in Dhanori, Pune', 'Browse the Spot 11 Enjoy menu. Verified dishes and prices will be added soon.'); return <><PageHero eyebrow="02 / The menu" title={<>Something good<br /><i>is on its way.</i></>} description="We are preparing the complete Spot 11 Enjoy menu with verified dishes, descriptions and prices." /><section className="section page-width menu-page"><div className="menu-toolbar"><div className="search-box"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search menu" aria-label="Search menu" /></div><div className="category-tabs" role="tablist">{categories.map(item => <button className={category === item ? 'active' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="menu-grid">{filtered.length ? filtered.map(item => <article className="menu-item" key={item.id}><div className="menu-item-art">Dish image to be added</div><div className="menu-item-info"><div><h3>{item.name}</h3><span className="status-pill">Details pending</span></div><p>{item.description || 'Description to be added.'}</p><strong>{item.price ? `₹${item.price}` : 'Price to be added'}</strong></div></article>) : <EmptyState title="Menu details coming soon" description="Verified dishes and prices will appear here." />}</div></section></> }
function OffersPage() { usePageMeta('Offers & Deals | Spot 11 Enjoy Pune', 'Current offers at Spot 11 Enjoy will be listed here when verified.'); return <><PageHero eyebrow="03 / Offers" title={<>Good reasons<br /><i>to come together.</i></>} description="Current offers and seasonal moments will be listed here once confirmed by the restaurant." /><ListingPage items={offers} empty="New offers coming soon." /></> }
function EventsPage() { usePageMeta('Events at Spot 11 Enjoy | Dhanori Pune', 'Live music and weekend events at Spot 11 Enjoy take place every Saturday and Sunday.'); return <><PageHero eyebrow="04 / Events" title={<>Make a night<br /><i>of it.</i></>} description="Join us every Saturday and Sunday for live music, celebrations and special nights at Spot 11 Enjoy." /><ListingPage items={events} empty="Weekend live music and events are updated here." /></> }
function ListingPage({ items, empty }: { items: { id: string; title: string; description?: string; status?: string }[]; empty: string }) { return <section className="section page-width listing-grid">{items.length ? items.map(item => <article className="listing-card" key={item.id}><div className="listing-art">Image to be added</div><div className="listing-copy"><span className="eyebrow">{item.status || 'To be updated'}</span><h3>{item.title}</h3><p>{item.description || 'Verified details will be added here.'}</p><span className="under-link">Details coming soon <ArrowRight size={16} /></span></div></article>) : <EmptyState title={empty} description="Check back for the latest updates." />}</section> }
function GalleryPage() { const [active, setActive] = useState<string | null>(null); const activeItem = galleryItems.find(item => item.id === active); usePageMeta('Gallery | Spot 11 Enjoy Pune', 'Restaurant photos and event videos from Spot 11 Enjoy will be added here.'); return <><PageHero eyebrow="05 / Gallery" title={<>A seat at<br /><i>the table.</i></>} description="Restaurant photography, food and event videos will be added here as verified media becomes available." /><section className="section page-width gallery-page"><div className="gallery-filters"><button className="active">All</button><button>Food</button><button>Ambience</button><button>Events</button><button>Videos</button></div><div className="gallery-grid">{galleryItems.map((item, index) => <button className={`gallery-tile ${index % 3 === 0 ? 'large' : ''}`} key={item.id} onClick={() => setActive(item.id)}>{item.src ? <img src={item.src} alt={item.alt} loading="lazy" /> : null}<span>{item.type === 'video' ? <Play size={18} /> : null}{item.title}</span></button>)}</div></section><AnimatePresence>{active && <div className="lightbox" onClick={() => setActive(null)}><button aria-label="Close gallery"><X /></button>{activeItem?.src ? <img src={activeItem.src} alt={activeItem.alt} /> : <p>Media preview to be added</p>}</div>}</AnimatePresence></> }
function ReviewsPage() { const [page, setPage] = useState(1); const pageSize = 3; const totalPages = Math.ceil(reviews.length / pageSize); const visibleReviews = reviews.slice((page - 1) * pageSize, page * pageSize); usePageMeta('Spot 11 Enjoy Reviews | Dhanori Pune', 'Read verified customer reviews for Spot 11 Enjoy.'); return <><PageHero eyebrow="06 / Reviews" title={<>Worth coming back<br /><i>for.</i></>} description="A selection of customer reviews shared about Spot 11 Enjoy." /><section className="section page-width reviews-page"><div className="rating-placeholder"><Star size={28} /><strong>{restaurantConfig.rating}</strong><span>Customer rating<br />Based on {restaurantConfig.reviewCount} reviews</span><a className="under-link" href="https://spot-11-enjoy.placejoys.com/#reviews" target="_blank" rel="noreferrer">View source <ArrowRight size={15} /></a></div><div className="review-tiles">{visibleReviews.map(review => <article className="review-tile" key={review.id}><div className="review-tile-top"><span className="review-stars" aria-label={`${review.rating} out of 5 stars`}>{'★'.repeat(review.rating)}</span><span className="review-source">Customer review</span></div><p>“{review.text}”</p><div className="review-author"><strong>{review.author}</strong><span>{review.date}</span></div></article>)}</div><div className="review-pagination"><button type="button" onClick={() => setPage(current => Math.max(1, current - 1))} disabled={page === 1}>Previous</button><span>Page {page} of {totalPages}</span><button type="button" onClick={() => setPage(current => Math.min(totalPages, current + 1))} disabled={page === totalPages}>Next</button></div><p className="review-disclaimer">Reviews are reproduced from a public restaurant listing and are not independently edited.</p></section></> }
function ContactPage() { usePageMeta('Contact Spot 11 Enjoy | Dhanori Pune', 'Find and contact Spot 11 Enjoy in Gini Belvista, Dhanori, Pune.'); return <><PageHero eyebrow="07 / Contact" title={<>Come find<br /><i>your spot.</i></>} description="We are in Gini Belvista, D.N. Parande Park, Dhanori, Pune, Maharashtra 411015." /><section className="section page-width contact-layout"><div className="contact-card"><p className="eyebrow">The address</p><h2>Spot 11<br /><i>Enjoy.</i></h2><p>{restaurantConfig.address.map(part => <span key={part}>{part}<br /></span>)}</p><div className="button-row"><a className="button button-gold" href={restaurantConfig.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <MapPin size={16} /></a><a className="button button-outline" href={`tel:${restaurantConfig.phone}`}>Call restaurant <Phone size={16} /></a></div></div><div className="map-placeholder"><iframe title="Spot 11 Enjoy location map" src={restaurantConfig.googleMapsEmbedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="map-caption"><MapPin size={17} /> Spot 11 Enjoy · Dhanori, Pune</div></div></section></> }
function ReservationPage() { const [submitted, setSubmitted] = useState(false); usePageMeta('Reserve a Table | Spot 11 Enjoy Pune', 'Request a table at Spot 11 Enjoy via WhatsApp.'); return <><PageHero eyebrow="08 / Reservations" title={<>Make room for<br /><i>a good time.</i></>} description="Send a reservation request through WhatsApp. Your request is not saved until the restaurant confirms it." /><section className="section page-width reservation-layout"><div><p className="eyebrow">Reservation request</p><h2>Tell us about<br /><i>your evening.</i></h2><p className="lead">Choose a date, time and party size. We’ll pass the details to the restaurant for confirmation.</p></div>{submitted ? <div className="success-panel"><Check size={22} /><h3>Request prepared.</h3><p>Your WhatsApp message has been opened. Please wait for confirmation from Spot 11 Enjoy.</p></div> : <ReservationForm onSubmit={() => setSubmitted(true)} />}</section></> }
function ReservationForm({ onSubmit }: { onSubmit: () => void }) { return <form className="reservation-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const message = `Hello Spot 11 Enjoy,\n\nI would like to reserve a table.\n\nName: ${data.get('name')}\nDate: ${data.get('date')}\nTime: ${data.get('time')}\nGuests: ${data.get('guests')}\nOccasion: ${data.get('occasion')}\nSpecial request: ${data.get('request') || 'None'}`; window.open(`https://wa.me/${restaurantConfig.whatsapp}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer'); onSubmit() }}><label>Name<input required name="name" /></label><div className="form-row"><label>Date<input required type="date" name="date" /></label><label>Time<input required type="time" name="time" /></label></div><div className="form-row"><label>Guests<select required name="guests"><option value="">Select</option><option>2</option><option>3–4</option><option>5–8</option><option>9+</option></select></label><label>Occasion<select name="occasion"><option>Not specified</option><option>Birthday</option><option>Anniversary</option><option>Family gathering</option><option>Corporate</option><option>Party</option><option>Dinner</option><option>Other</option></select></label></div><label>Special request<textarea name="request" rows={4} /></label><button className="button button-gold" type="submit">Continue on WhatsApp <MessageCircle size={16} /></button><small>We’ll open WhatsApp with your request. The restaurant will confirm availability directly.</small></form> }
function EmptyPage({ title, description }: { title: string; description: string }) { return <><PageHero eyebrow="Spot 11 Enjoy" title={<>{title}</>} description={description} /><div className="section page-width"><EmptyState title={title} description={description} /></div></> }
function EmptyState({ title, description }: { title: string; description: string }) { return <div className="empty-state"><Clock3 size={23} /><h3>{title}</h3><p>{description}</p><Link className="under-link" to="/contact">Contact the restaurant <ArrowRight size={16} /></Link></div> }
function FloatingActions() { return <div className="floating-actions"><a href={`tel:${restaurantConfig.phone}`} aria-label="Call restaurant"><Phone size={17} /></a><a href={`https://wa.me/${restaurantConfig.whatsapp}`} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={17} /></a><Link to="/reservation" aria-label="Reserve a table"><CalendarDays size={17} /></Link></div> }
function Footer() { return <footer className="site-footer"><div className="page-width footer-grid"><div><Link className="brand" to="/"><span className="brand-mark">11</span><span><strong>SPOT</strong><em>ENJOY</em></span></Link><p className="footer-note">Family restaurant · bar · dining<br />Dhanori, Pune</p></div><div><span className="footer-label">Explore</span>{navItems.slice(0, 4).map(([label, path]) => <Link key={path} to={path}>{label}</Link>)}</div><div><span className="footer-label">Connect</span><a href={`tel:${restaurantConfig.phone}`}>{restaurantConfig.phone}</a><a href={restaurantConfig.googleMapsUrl} target="_blank" rel="noreferrer">Get directions</a><a href={restaurantConfig.swiggyUrl} target="_blank" rel="noreferrer">Order on Swiggy</a><a href={restaurantConfig.zomatoUrl} target="_blank" rel="noreferrer">Order on Zomato</a>{restaurantConfig.email && <a href={`mailto:${restaurantConfig.email}`}>{restaurantConfig.email}</a>}</div><div><span className="footer-label">Stay in touch</span><p>Verified updates and restaurant news will appear here.</p><div className="socials">{restaurantConfig.instagramUrl && <a href={restaurantConfig.instagramUrl}>Instagram</a>}{restaurantConfig.facebookUrl && <a href={restaurantConfig.facebookUrl}>Facebook</a>}{restaurantConfig.youtubeUrl && <a href={restaurantConfig.youtubeUrl}>YouTube</a>}</div></div></div><div className="page-width footer-bottom"><span>© {new Date().getFullYear()} Spot 11 Enjoy</span><span>Content to be added · Made for good company</span></div></footer> }

export default App
